import { vars } from "@/styles/global.css";
import { createSprinkles, defineProperties } from "@vanilla-extract/sprinkles";

const conditions = {
  mobile: {},
  tablet: { "@media": "screen and (min-width: 768px)" },
  desktop: { "@media": "screen and (min-width: 1024px)" },
} as const;

const spacing = {
  0: "0",
  2: vars.space[2],
  3: vars.space[3],
  4: vars.space[4],
  5: vars.space[5],
  6: vars.space[6],
  8: vars.space[8],
} as const;

const size = {
  auto: "auto",
  full: "100%",
  fit: "fit-content",
  min: "min-content",
  max: "max-content",
} as const;

const columns = {
  1: "repeat(1, minmax(0, 1fr))",
  2: "repeat(2, minmax(0, 1fr))",
  3: "repeat(3, minmax(0, 1fr))",
  4: "repeat(4, minmax(0, 1fr))",
  6: "repeat(6, minmax(0, 1fr))",
  12: "repeat(12, minmax(0, 1fr))",
  autoSm: "repeat(auto-fit, minmax(160px, 1fr))",
  autoMd: "repeat(auto-fit, minmax(220px, 1fr))",
  sidebar: "minmax(220px, 280px) minmax(0, 1fr)",
} as const;

// const fontSize = {
//   xs: vars.text.size.xs,
//   sm: vars.text.size.sm,
//   md: vars.text.size.md,
//   lg: vars.text.size.lg,
//   xl: vars.text.size.xl,
//   "2xl": vars.text.size["2xl"],
//   "3xl": vars.text.size["3xl"],
// } as const;

const typography = {
  heading01: {
    fontFamily: vars.font.display,
    fontSize: vars.text.size.hero,
    fontWeight: vars.text.weight.bold,
    lineHeight: "0.98",
    letterSpacing: "-0.05em",
  },
  heading02: {
    fontFamily: vars.font.display,
    fontSize: vars.text.size["2xl"],
    lineHeight: vars.text.lineHeight.compact,
    fontWeight: vars.text.weight.bold,
    letterSpacing: vars.text.tracking.tight,
  },
  heading03: {
    fontFamily: vars.font.display,
    fontSize: vars.text.size.xl,
    lineHeight: vars.text.lineHeight.heading,
    fontWeight: vars.text.weight.semibold,
    letterSpacing: vars.text.tracking.tight,
  },
  heading04: {
    fontFamily: vars.font.display,
    fontSize: vars.text.size.lg,
    lineHeight: vars.text.lineHeight.heading,
    fontWeight: vars.text.weight.semibold,
    letterSpacing: vars.text.tracking.snug,
  },
  body01: {
    fontFamily: vars.font.body,
    fontSize: vars.text.size.md,
    lineHeight: vars.text.lineHeight.body,
    fontWeight: vars.text.weight.regular,
    letterSpacing: vars.text.tracking.normal,
  },
  body02: {
    fontFamily: vars.font.body,
    fontSize: vars.text.size.sm,
    lineHeight: vars.text.lineHeight.body,
    fontWeight: vars.text.weight.regular,
    letterSpacing: vars.text.tracking.normal,
  },
  body03: {
    fontFamily: vars.font.body,
    fontSize: vars.text.size.xs,
    lineHeight: vars.text.lineHeight.body,
    fontWeight: vars.text.weight.regular,
    letterSpacing: vars.text.tracking.normal,
  },
  label01: {
    fontFamily: vars.font.body,
    fontSize: vars.text.size.md,
    lineHeight: vars.text.lineHeight.heading,
    fontWeight: vars.text.weight.semibold,
    letterSpacing: vars.text.tracking.normal,
  },
  label02: {
    fontFamily: vars.font.body,
    fontSize: vars.text.size.sm,
    lineHeight: vars.text.lineHeight.heading,
    fontWeight: vars.text.weight.semibold,
    letterSpacing: vars.text.tracking.normal,
  },
  label03: {
    fontFamily: vars.font.body,
    fontSize: vars.text.size.xs,
    lineHeight: vars.text.lineHeight.heading,
    fontWeight: vars.text.weight.semibold,
    letterSpacing: vars.text.tracking.wide,
    textTransform: "uppercase",
  },
  overline01: {
    fontFamily: vars.font.display,
    fontSize: vars.text.size.xs,
    fontWeight: vars.text.weight.bold,
    lineHeight: vars.text.lineHeight.heading,
    letterSpacing: vars.text.tracking.caps,
    textTransform: "uppercase",
  },
  code01: {
    fontFamily: vars.font.mono,
    fontSize: vars.text.size.sm,
    fontWeight: vars.text.weight.medium,
    lineHeight: vars.text.lineHeight.relaxed,
    fontVariantLigatures: "none",
  },
} as const;

const layoutProperties = defineProperties({
  conditions,
  defaultCondition: "desktop",
  properties: {
    typography,
    display: ["none", "block", "inline-block", "inline-flex", "flex", "grid"],
    position: ["static", "relative", "absolute", "sticky", "fixed"],
    overflow: ["hidden", "auto", "scroll", "visible"],
    overflowX: ["hidden", "auto", "scroll", "visible"],
    overflowY: ["hidden", "auto", "scroll", "visible"],
    width: size,
    minWidth: { 0: "0", ...size },
    maxWidth: { none: "none", full: "100%", prose: "72ch" },
    height: size,
    minHeight: { 0: "0", full: "100%", screen: "100vh" },
    maxHeight: { none: "none", full: "100%", screen: "100vh" },
    flexDirection: ["row", "row-reverse", "column", "column-reverse"],
    flexWrap: ["nowrap", "wrap", "wrap-reverse"],
    justifyContent: [
      "flex-start",
      "center",
      "flex-end",
      "space-between",
      "space-around",
      "space-evenly",
    ],
    alignItems: ["stretch", "flex-start", "center", "flex-end", "baseline"],
    alignContent: [
      "stretch",
      "flex-start",
      "center",
      "flex-end",
      "space-between",
    ],
    alignSelf: [
      "auto",
      "stretch",
      "flex-start",
      "center",
      "flex-end",
      "baseline",
    ],
    justifySelf: ["auto", "start", "center", "end", "stretch"],
    justifyItems: ["start", "center", "end", "stretch"],
    placeItems: ["start", "center", "end", "stretch"],
    placeSelf: ["auto", "start", "center", "end", "stretch"],
    flexGrow: [0, 1],
    flexShrink: [0, 1],
    flexBasis: {
      auto: "auto",
      full: "100%",
      half: "50%",
      third: "33.333333%",
      quarter: "25%",
    },
    gap: spacing,
    rowGap: spacing,
    columnGap: spacing,
    paddingTop: spacing,
    paddingRight: spacing,
    paddingBottom: spacing,
    paddingLeft: spacing,
    marginTop: { auto: "auto", ...spacing },
    marginRight: { auto: "auto", ...spacing },
    marginBottom: { auto: "auto", ...spacing },
    marginLeft: { auto: "auto", ...spacing },
    inset: spacing,
    top: spacing,
    right: spacing,
    bottom: spacing,
    left: spacing,
    gridTemplateColumns: columns,
    gridAutoFlow: ["row", "column", "dense", "row dense", "column dense"],
    letterSpacing: {
      tight: vars.text.tracking.tight,
      snug: vars.text.tracking.snug,
      normal: vars.text.tracking.normal,
      wide: vars.text.tracking.wide,
      caps: vars.text.tracking.caps,
    },
    textAlign: ["left", "center", "right"],
    textTransform: ["none", "uppercase"],
    gridColumn: {
      auto: "auto",
      span1: "span 1 / span 1",
      span2: "span 2 / span 2",
      span3: "span 3 / span 3",
      span4: "span 4 / span 4",
      span6: "span 6 / span 6",
      full: "1 / -1",
    },
    gridRow: {
      auto: "auto",
      span1: "span 1 / span 1",
      span2: "span 2 / span 2",
      span3: "span 3 / span 3",
      full: "1 / -1",
    },
  },
  shorthands: {
    p: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    px: ["paddingLeft", "paddingRight"],
    py: ["paddingTop", "paddingBottom"],
    m: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    mx: ["marginLeft", "marginRight"],
    my: ["marginTop", "marginBottom"],
  },
});

export const sprinkles = createSprinkles(layoutProperties);
export type Sprinkles = Parameters<typeof sprinkles>[0];

export const sprinklePropNames = [
  "display",
  "position",
  "overflow",
  "overflowX",
  "overflowY",
  "width",
  "minWidth",
  "maxWidth",
  "height",
  "minHeight",
  "maxHeight",
  "flexDirection",
  "flexWrap",
  "justifyContent",
  "alignItems",
  "alignContent",
  "alignSelf",
  "justifySelf",
  "justifyItems",
  "placeItems",
  "placeSelf",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "gap",
  "rowGap",
  "columnGap",
  "paddingTop",
  "paddingRight",
  "paddingBottom",
  "paddingLeft",
  "marginTop",
  "marginRight",
  "marginBottom",
  "marginLeft",
  "inset",
  "top",
  "right",
  "bottom",
  "left",
  "gridTemplateColumns",
  "gridAutoFlow",
  "fontFamily",
  "fontSize",
  "fontWeight",
  "lineHeight",
  "letterSpacing",
  "textAlign",
  "textTransform",
  "gridColumn",
  "gridRow",
  "p",
  "px",
  "py",
  "m",
  "mx",
  "my",
] as const;
